### ISSUE TITLE
Fatal error when message not well formated

### ISSUE THREAD

**Issue by ddurieux** [shinken-monitoring/mod-nsca#7]
```
[nsca] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/usr/local/libexec/shinken/modules/nsca/module.py", line 213, in main
    self.process_check_result(databuffer[s], IVs[s])
  File "/usr/local/libexec/shinken/modules/nsca/module.py", line 164, in process_check_result
    (timestamp, rc, hostname, service, output) = self.read_check_result(databuffer, IV, payload_length)
  File "/usr/local/libexec/shinken/modules/nsca/module.py", line 136, in read_check_result
    struct.unpack(unpackFormat, data)
error: bad char in struct format
```

**Comment by mohierf** [comment]
Should try to catch the exception to avoid module break ... and to make a log of the bad message ?

**Comment by ddurieux** [comment]
It's difficult to log the bad message because this error mean the unpack binary message failed

**Comment by mohierf** [comment]
Should log byte per byte ?

**Comment by ddurieux** [comment]
Possible, but it's a very long chain and in binary, andvery hard to unpack if you don't have the pack string
