### ISSUE TITLE
Socket accept exception (Err 53) not catched ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-nsca#9]
Regularly the receiver module goes down because of an exception

```
[1440607568] ERROR: [receiver-master] [nsca] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/usr/local/libexec/shinken/modules/nsca/module.py", line 217, in main
    client, _ = server.accept()
  File "/usr/local/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 53] Software caused connection abort
```

**Comment by mohierf** [comment]
On FreeBSD this exception is raised by the server because a client closed a pending socket before it has been opened ... indeed it does not seem to be a bug!

The module should catch this exception for not going down ...
